export const cargarInformacionCandidatosCipa = [
  {
    nombre: 'Z Maria Mendoza',
    email: 'Z mm@gmail.com',
    telefono: '465464654',
    perfil: 'programador',
    en_plantilla: false,
    fecha_ultima_actualizacion: new Date(2019, 1, 25),
    fechaVencimiento: null,
  },
  {
    nombre: 'X Luisa Ojeda',
    email: 'AA lo@gmail.com',
    telefono: '658464132',
    perfil: 'programador',
    en_plantilla: true,
    fecha_ultima_actualizacion: new Date(2019, 5, 5),
    fechaVencimiento: null,
  },
  {
    nombre: 'B Javier Hernande',
    email: 'B jehk@gmail.com',
    telefono: '645632111',
    perfil: 'arquitecto devop',
    en_plantilla: false,
    fecha_ultima_actualizacion: new Date(2019, 5, 11),
    fechaVencimiento: null,
  },
  {
    nombre: 'A Rocio Canales',
    email: 'A rocio.canales@alvea.es',
    telefono: '652488965',
    perfil: 'programador',
    en_plantilla: true,
    fecha_ultima_actualizacion: new Date(2019, 2, 11),
    fechaVencimiento: null,
  },
  {
    nombre: 'AA Javier Hernande',
    email: 'X jehk@gmail.com',
    telefono: '645632111',
    perfil: 'arquitecto devop',
    en_plantilla: false,
    fecha_ultima_actualizacion: new Date(2019, 5, 11),
    fechaVencimiento: null,
  },
  {
    nombre: 'AA Javier Hernande',
    email: 'X jehk@gmail.com',
    telefono: '645632111',
    perfil: 'arquitecto devop',
    en_plantilla: false,
    fecha_ultima_actualizacion: new Date(2020, 7, 11),
    fechaVencimiento: null,
  },
];
