export const candidates = [
  {
    id: 1,
    name: 'Leónidas',
    email: 'leonidas@email.com',
    age: 25,
    phone: 985475263,
    location: 'Madrid',
    experience: 5,
    tags: ['html', 'css', 'javascript'],
    salary: '1600',
    onStaff: true,
    profile: 'Programmer',
    language: 'B2',
    lastUpdate: '01/01/2019',
    expirationDate: '01/07/2020',
    light: true
  },
  {
    id: 2,
    name: 'Gorgo',
    email: 'gorgo@email.com',
    age: 36,
    phone: 985415869,
    location: 'Sevilla',
    experience: 10,
    tags: ['systems', 'servers'],
    salary: '2100',
    onStaff: false,
    profile: 'Arquitect',
    language: 'C1',
    lastUpdate: '02/01/2019',
    expirationDate: '02/07/2020',
    light: false
  },
  {
    id: 3,
    name: 'Dilios',
    email: 'dilios@email.com',
    age: 27,
    phone: 985411425,
    location: 'Barcelona',
    experience: 6,
    tags: ['psychology', 'relationships'],
    salary: '2000',
    onStaff: true,
    profile: 'RRHH',
    language: 'C2',
    lastUpdate: '03/01/2019',
    expirationDate: '03/07/2020',
    light: false
  },
  {
    id: 4,
    name: 'Theron',
    email: 'theron@email.com',
    age: 40,
    phone: 985489754,
    location: 'Galicia',
    experience: 20,
    tags: ['systems', 'security'],
    salary: '2500',
    onStaff: false,
    profile: 'Analyst',
    language: 'C2+',
    lastUpdate: '04/01/2019',
    expirationDate: '04/07/2020',
    light: true
  }
];
