export const getDatosReporteMesesHceap = (idEmpleado, proyecto, year) => {
  /* FORMATO QUE DEBE RECIBIR Nombre="String", Email="String", telefono="String/Number", perfil="String", en_plantilla="boolean"(true="SI",false="NO"), fecha_ultima_actualizacion="STRING"(formato(dd/mm/yyyy)) */
  // BUSCAR ID_EMPLEADO > PROYECTO > AÑO > (DEVOLVER EN UN JSON DATOS DE CADA MES DE ESE AÑO EJ: [ {mes: "Enero", Horas_trabajadas_ese_mes: "176", horas_permiso: "0", horas_intervenciones: "0", jornadas_trabajadas: "22", jornadas_guardia: "0", jornadas_vacaciones: "0"},{mes: "Febrero", Horas_trabajadas_ese_mes: "176", horas_permiso: "0", horas_intervenciones: "0", jornadas_trabajadas: "22", jornadas_guardia: "0", jornadas_vacaciones: "0"}]) y asi rellenar el array con todos los meses del año que contenga algun dato.
  return [{ mes: 'febrero', horas_trabajadas: '176', horas_permiso: '10', horas_intervenciones: '20', jornadas_trabajadas: '22', jornadas_guardia: '2', jornadas_vacaciones: '3' }, { mes: 'enero', horas_trabajadas: '176', horas_permiso: '10', horas_intervenciones: '20', jornadas_trabajadas: '22', jornadas_guardia: '2', jornadas_vacaciones: '3' }, { mes: 'marzo', horas_trabajadas: '176', horas_permiso: '10', horas_intervenciones: '20', jornadas_trabajadas: '22', jornadas_guardia: '2', jornadas_vacaciones: '3' }, { mes: 'abril', horas_trabajadas: '176', horas_permiso: '10', horas_intervenciones: '20', jornadas_trabajadas: '22', jornadas_guardia: '2', jornadas_vacaciones: '3' }, { mes: 'mayo', horas_trabajadas: '176', horas_permiso: '10', horas_intervenciones: '20', jornadas_trabajadas: '22', jornadas_guardia: '2', jornadas_vacaciones: '3' }, { mes: 'junio', horas_trabajadas: '176', horas_permiso: '10', horas_intervenciones: '20', jornadas_trabajadas: '22', jornadas_guardia: '2', jornadas_vacaciones: '3' }, { mes: 'julio', horas_trabajadas: '176', horas_permiso: '10', horas_intervenciones: '20', jornadas_trabajadas: '22', jornadas_guardia: '2', jornadas_vacaciones: '3' }, { mes: 'agosto', horas_trabajadas: '176', horas_permiso: '10', horas_intervenciones: '20', jornadas_trabajadas: '22', jornadas_guardia: '2', jornadas_vacaciones: '3' }, { mes: 'septiembre', horas_trabajadas: '176', horas_permiso: '10', horas_intervenciones: '20', jornadas_trabajadas: '22', jornadas_guardia: '2', jornadas_vacaciones: '3' }, { mes: 'octubre', horas_trabajadas: '176', horas_permiso: '10', horas_intervenciones: '20', jornadas_trabajadas: '22', jornadas_guardia: '2', jornadas_vacaciones: '3' }, { mes: 'noviembre', horas_trabajadas: '176', horas_permiso: '10', horas_intervenciones: '20', jornadas_trabajadas: '22', jornadas_guardia: '2', jornadas_vacaciones: '3' }, { mes: 'diciembre', horas_trabajadas: '176', horas_permiso: '10', horas_intervenciones: '20', jornadas_trabajadas: '22', jornadas_guardia: '2', jornadas_vacaciones: '3' }];
};

export const cargarEmpleadosHceap = () => {
  // HACER CONSULTA AJAX QUE RPEGUNTE POR TODOS LOS EMPLEADOS, NOMBRE Y SU ID;
  return [{ nombre: 'Natanael Beniamin Cioarba', id_empleado: 'EMP_301' }, { nombre: 'Abel Lawfa awfawfa', id_empleado: 'EMP_302' }, { nombre: 'Miriam', id_empleado: 'EMP_303' }, { nombre: 'Juan del Castillo', id_empleado: 'EMP_304' }];
};

export const getProyectosAsigandosEmpleado = (idEmpleado) => {
  /* HACER CONSULTA AJAX QUE PREGUNTE POR LOS PROYECTOS EN LOS QUE ESTUVO ASIGNADO EL ID DEL EMPLEADO */
  return ['Estructura', 'Cliente', 'Intranet', 'Diseño', 'Plantilla nueva'];
};
